CREATE TABLE [dbo].[PROPERTY_TYPE]
(
	[Type] nvarchar(12) NOT NULL PRIMARY KEY
)

CREATE TABLE [dbo].[INVOICE_TYPE]
(
	[Type] nvarchar(12) NOT NULL PRIMARY KEY
)

CREATE TABLE [dbo].[LANDLORD]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL, 
	[Street] NVARCHAR(50) NOT NULL,
    [City] NVARCHAR(50) NOT NULL, 
    [State] NVARCHAR(50) NOT NULL, 
    [Zip] INT NOT NULL, 
    [Phone] NCHAR(10) NOT NULL, 
    [Email] NVARCHAR(50) NOT NULL
)


CREATE TABLE [dbo].[PROPERTY]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Lord_ID] int NOT NULL DEFAULT 1,
	[Street] nvarchar(50) NOT NULL,
	[City] nvarchar(50) NOT NULL,
	[State] nvarchar(50) NOT NULL,
	[Zip] int NOT NULL,
	[Value] FLOAT,
	[Description] nvarchar(max),
	[Type] nvarchar(12),
	CONSTRAINT PROPERTY_LANDLORD_FK
	FOREIGN KEY(Lord_ID) REFERENCES LANDLORD(ID) ON DELETE SET DEFAULT ON UPDATE CASCADE,
	CONSTRAINT PROPERTY_PROPTYPE_FK
	FOREIGN KEY(Type) REFERENCES PROPERTY_TYPE(Type) ON DELETE SET NULL ON UPDATE CASCADE
)


CREATE TABLE [dbo].[LEASE]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Prop_ID] INT NOT NULL,
	[Start_date] date,
	[Duration_months] int,
	[Monthly_rent] FLOAT
	CONSTRAINT LEASE_PROPERTY_FK
	FOREIGN KEY(Prop_ID) REFERENCES PROPERTY(ID) ON DELETE CASCADE ON UPDATE CASCADE
)


CREATE TABLE [dbo].[TENANT]
(
    [ID] INT PRIMARY KEY,
	[Prop_ID] INT DEFAULT 0,
	[Name] nvarchar(30) NOT NULL,
	[Phone] char(10),
	[Email] nvarchar(30),
	[Registration_date] date NOT NULL,
	CONSTRAINT TENANT_PROPERTY_FK
	FOREIGN KEY(Prop_ID) REFERENCES PROPERTY(Id) ON DELETE SET NULL ON UPDATE NO ACTION
)


CREATE TABLE [dbo].[INVOICE]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[Prop_ID] int,
	[Date_issued] date,
	[Date_paid] date,
	[Description] nvarchar(max),
	[Cost] FLOAT,
	[Type] nvarchar(12),
	CONSTRAINT INVOICE_PROPERTY_FK
	FOREIGN KEY(Prop_ID) REFERENCES PROPERTY(ID) ON UPDATE CASCADE,
	CONSTRAINT INVOICE_INVTYPE_FK
	FOREIGN KEY(Type) REFERENCES INVOICE_TYPE(Type) ON DELETE SET NULL ON UPDATE CASCADE
)

